version: 2.1

executors:
  terraform:
    resource_class: small
    shell: /bin/bash -eo pipefail
    working_directory: /terraform-workspace-type
    docker:
      - image: jinugasachio/circleci-terraform:1.1.2

jobs:
  assume_role:
    executor: terraform
    steps:
      - checkout
      - run: 
          name: Assume role
          command: ./scripts/circleci/assume_role.sh
      - persist_to_workspace: # GAと違いCircleCIでは動的なmatrix buildができなそうなのでworkspace使う必要は本当はない
          root: /tmp
          paths:
            - aws_sts_credentials.json

  lint:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Run terraform fmt
          command: terraform fmt -diff -check -recursive .
      - attach_workspace:
          at: /tmp
      - run:
          name: Export credentials
          command: ./scripts/circleci/export_credentials.sh
      - run:
          name: Run tflint init
          command: tflint --init --config ./.tflint.hcl
      - run:
          name: Run tflint
          command: |
            changed_dirs=$(./scripts/circleci/detect_changed_dirs.sh)
            ./scripts/circleci/tflint.sh $changed_dirs

  terraform_plan:
    executor: terraform
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Export credentials
          command: ./scripts/circleci/export_credentials.sh
      - run: aws s3 ls
      - run:
          name: Run terraform init
          command: |
            changed_dirs=$(./scripts/circleci/detect_changed_dirs.sh)
            ./scripts/circleci/terraform_init.sh $changed_dirs
      - run:
          name: Run terraform validate
          command: |
            changed_dirs=$(./scripts/circleci/detect_changed_dirs.sh)
            ./scripts/circleci/terraform_validate.sh $changed_dirs
      - run:
          name: Run terraform plan
          command: |
            # echo 'export PULL_REQUEST_NUMBER=${CIRCLE_PULL_REQUEST##*/}' >> $BASH_ENV
            # source $BASH_ENV
            changed_dirs=$(./scripts/circleci/detect_changed_dirs.sh)
            ./scripts/circleci/terraform_plan.sh $changed_dirs
          environment:
            GITHUB_TOKEN: $GITHUB_TOKEN_FOR_CIRCLECI
            PULL_REQUEST_NUMBER: ${CIRCLE_PULL_REQUEST##*/}
            REPOSITORY_OWNER: $CIRCLE_PROJECT_USERNAME
            REPOSITORY_NAME: $CIRCLE_PROJECT_REPONAME

  security_check:
    executor: terraform
    steps:
      - checkout
      - run:
          name: Run tfsec
          command: tfsec --force-all-dirs --config-file ./.tfsec/config.yml # この命名規則であれば自動で読み込まれるが明示しておく https://aquasecurity.github.io/tfsec/v0.63.1/getting-started/configuration/config/
  
workflows:
  version: 2
  terraform_workflow:
    jobs:
      # - security_check
      - assume_role
      - lint:
          requires:
            - assume_role
      - terraform_plan:
          requires:
            - lint