version: 2.1

executors:
  terraform:
    resource_class: small
    shell: /bin/bash -eo pipefail
    working_directory: ~/terraform-workspace-type
    docker:
      - image: jinugasachio/circleci-terraform:1.1.2

jobs:
  assume_role:
    executor: terraform
    steps:
      - checkout
      - run: 
          name: Assume role
          command: ./scripts/circleci/assume_role.sh
      - persist_to_workspace:
          root: /tmp
          paths:
            - aws_sts_credentials.json

  export_credentials:
    executor: terraform
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Export credentials
          command: ./scripts/circleci/export_credentials.sh
  
workflows:
  version: 2
  terraform_workflow:
    jobs:
      - assume_role
      - export_credentials:
          requires:
            - assume_role
